# Week 1: Pandas Series

## pandas Series

In [2]:
import pandas as pd
import numpy as np

A pandas.Series having an index is the main difference between a pandas.Series and a NumPy array:

In [3]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[ 0.3433319   1.13458996 -2.17533947  0.67665103]

<class 'pandas.core.series.Series'>
0    0.343332
1    1.134590
2   -2.175339
3    0.676651
dtype: float64

In [5]:
# Basic method of create a pandas Series
# s = pd.Series(data, index=index)

The data parameter can be:
- a list or NumPy array,
- a Python dictionary, or
- a single number, boolean (True/False), or string.
  
The index parameter is optional. If we wish to include it, it must be a list of indices of the same length as data.

## Creating a pandas Series

In [6]:
# Example: Creating a pandas Series from a np array
pd.Series(np.arange(3), index=[2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

In [8]:
# Example: Creating a pandas Series from a python list (default index)
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [9]:
# Example: Creating a pandas Series from a python dictionary
# Make dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}
# Initialize series w/ dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [10]:
# Example: Creating a pandas Series from a single value
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

## Simple Operations

In [14]:
# Initialize a pandas Series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in the series by 10
print(s /10, '\n')

# Take the exponential of each element in the series
print(np.exp(s), '\n')

# Print original Series
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [15]:
# Can produce new pandas Series w/ conditionals
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

## Identifying Missing Values

In pandas we can represent a missing, NULL, or NA value with the float value numpy.nan, which stands for “not a number”.

In [16]:
# pandas Series with NaNs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [18]:
# Check if pandas Series has any NaNs using hasnans attribute
s.hasnans

True

In [19]:
# Check pandas Series for NA values, returns Series
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

### Check-In

1. The integer number -999 is often used to represent missing values. Create a pandas.Series named s with four integer values, two of which are -999. The index of this series should be the letters A through D.
2. In the pandas.Series documentation, look for the method mask(). Use this method to update the series s so that the -999 values are replaced by NA values. HINT: check the first example in the method’s documentation.

In [23]:
# Create pandas Series for #1
s = pd.Series([5,-999,8,-999], index = ['A','B','C','D'])
s

A      5
B   -999
C      8
D   -999
dtype: int64

In [28]:
# Apply mask to Series to change -999 to NA
s_clean = s.mask(s == -999, other = "NA")
s_clean

A     5
B    NA
C     8
D    NA
dtype: object

## Data Frames

It represents tabular data and we can think of it as a spreadsheet. Each column of a pandas.DataFrame is a pandas.Series.

### Creating a pandas DataFrame

In [30]:
# Initialize dictionary with column data (Series) 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [31]:
# Change index of df
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

### Check-In

1. We can access the data frame’s column names via the columns attribute. Update the column names to C1 and C2 by updating this attribute.

In [34]:
df.columns = ['C1','C2']
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3

## Lesson Summary

- A pandas.Series is a series of values that has an accessible index.
    - Multiple ways to create series.
    - Operations can be performed on series.
    - Index can be customized.
- A pandas.Dataframe is a tabular data type - like a spreadsheet - where each column is a pandas.Series.
    - Indexes (Rows) and Columns can be customized.